"""Regenerate every measured value the posts quote.

Ground truth before prose: no number in a post should exist unless this script
can produce it again. Run it and diff the output against verify/RESULTS.md.

    python verify/capture.py > verify/RESULTS.md

Requires the series SDK and the first-server project on the path:

    pip install "mcp[cli]==2.0.0b2" psutil httpx
    PYTHONPATH=code/05-first-server/src python verify/capture.py
"""

from __future__ import annotations

import asyncio
import json
import subprocess
import sys
from importlib.metadata import version
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "code" / "05-first-server" / "src"))


def h(title: str) -> None:
    print(f"\n## {title}\n")


def fence(text: str, lang: str = "") -> None:
    print(f"```{lang}\n{text.rstrip()}\n```")


async def capture() -> None:
    from mcp import Client
    from mcp_types import ElicitResult, ResourceTemplateReference

    from system_info import mcp

    print("# Verified results")
    print()
    print("Generated by `verify/capture.py`. Every figure quoted in a post should")
    print("appear here. If they disagree, the post is wrong.")

    h("Environment")
    print(f"- `mcp` {version('mcp')}")
    print(f"- `mcp-types` {version('mcp-types')}")
    print(f"- Python {sys.version.split()[0]}")

    async with Client(mcp) as c:
        # ---- the published surface -------------------------------------
        h("Published tool surface")
        print("| tool | input properties | output schema | annotations |")
        print("|---|---|---|---|")
        for t in (await c.list_tools()).tools:
            props = ", ".join((t.input_schema or {}).get("properties", {})) or "none"
            out = "yes" if t.output_schema else "**null**"
            ann = t.annotations
            flags = []
            if ann:
                if ann.read_only_hint:
                    flags.append("readOnly")
                if ann.destructive_hint:
                    flags.append("destructive")
                if ann.idempotent_hint:
                    flags.append("idempotent")
            print(f"| `{t.name}` | {props} | {out} | {', '.join(flags) or 'none'} |")

        # ---- the security property post 08 claims ----------------------
        h("The resolved parameter is invisible to the model")
        tools = {t.name: t for t in (await c.list_tools()).tools}
        published = sorted(tools["terminate_process"].input_schema["properties"])
        print("`terminate_process` takes an `approval` parameter resolved by elicitation.")
        print("Its published input schema is:")
        fence(json.dumps(published), "json")
        print()
        print("`approval` is absent, so a model cannot forge its own approval.")

        # ---- signature to schema, quoted by post 05 --------------------
        h("Signature to schema")
        print("`find_process(name: str, limit: int = 25)` publishes:")
        fence(json.dumps(tools["find_process"].input_schema, indent=2), "json")

        # ---- structured output ----------------------------------------
        h("Structured output")
        result = await c.call_tool("get_system_info", {})
        print(f"`resultType` is `{result.result_type}`. Structured content keys:")
        fence(json.dumps(sorted(result.structured_content), indent=2), "json")

        # ---- resources, templates, prompts, completions ----------------
        h("Resources, prompts, completions")
        for r in (await c.list_resources()).resources:
            print(f"- resource `{r.uri}` ({r.mime_type})")
        for t in (await c.list_resource_templates()).resource_templates:
            print(f"- template `{t.uri_template}`")
        for p in (await c.list_prompts()).prompts:
            args = ", ".join(a.name for a in (p.arguments or []))
            print(f"- prompt `{p.name}`({args})")
        comp = await c.complete(
            ref=ResourceTemplateReference(uri="system://disk/{disk}"),
            argument={"name": "disk", "value": "r"},
        )
        print(f"- completion for prefix `r` returns `{comp.completion.values}`")

        # ---- the allowlist defense -------------------------------------
        h("Resource template variables are untrusted")
        for uri in ("system://disk/etc", "system://disk/../../etc/passwd"):
            try:
                await c.read_resource(uri)
                outcome = "NO ERROR (unexpected)"
            except Exception as exc:  # noqa: BLE001 - reporting, not handling
                outcome = f"{type(exc).__name__}: {exc}"
            print(f"- `{uri}` -> {outcome}")

    # ---- the elicitation round trip --------------------------------------
    h("Elicitation outcomes")
    print("| user action | tool result |")
    print("|---|---|")
    for action, content in (
        ("accept", {"confirm": True}),
        ("accept", {"confirm": False}),
        ("decline", None),
        ("cancel", None),
    ):
        async def cb(context, params, _a=action, _c=content):
            return ElicitResult(action=_a, content=_c)

        async with Client(mcp, elicitation_callback=cb) as c2:
            r = await c2.call_tool("terminate_process", {"pid": 999999})
            label = f"{action} {json.dumps(content)}" if content else action
            print(f"| {label} | {r.content[0].text} |")

    # ---- the question is asked once, deterministically --------------------
    h("The elicitation question is derived from the arguments only")
    seen: list[str] = []

    async def record(context, params):
        seen.append(params.message)
        return ElicitResult(action="decline", content=None)

    async with Client(mcp, elicitation_callback=record) as c3:
        await c3.call_tool("terminate_process", {"pid": 4242})
    print(f"- asked {len(seen)} time(s)")
    print(f"- text: `{seen[0]}`")
    print()
    print("The SDK matches a recorded answer against a digest of this exact string.")
    print("A question containing a timestamp or a live reading would never match,")
    print("and the call would never converge.")

    # ---- the test suite ---------------------------------------------------
    h("Test suite")
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests", "-q"],
        cwd=ROOT / "code" / "05-first-server",
        capture_output=True,
        text=True,
        env={**__import__("os").environ, "PYTHONPATH": "src"},
    )
    fence(proc.stdout.strip().splitlines()[-1] if proc.stdout else "(no output)")


if __name__ == "__main__":
    asyncio.run(capture())
